export const enum Paths {
  Alerts = 'alerts',
  Example = 'example',
  Home = 'home',
  Library = 'library',
  Main = 'main',
  Profile = 'profile',
  Reader = 'reader',
  Search = 'search',
  Settings = 'settings',
  Startup = 'startup',
  Login = 'login',
  Admin = 'admin',
  Register = 'register',
  VerifyOtp = 'verify-otp',
  StoryDetail = 'story-detail',
  Streak = 'streak',
  Write = 'write',
}
